version: '3.7'
services:
  db:
    container_name: instamemo_db.postgres
    image: postgres:12.4
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  api:
    container_name: instamemo_api
    build: 
      context: backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./backend:/api"
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    container_name: instamemo_front
    build:
      context: frontend/
      target: 'develop-stage'
    volumes:
      - "./frontend:/app"
    working_dir: /app
    ports:
    - '8080:8080'
    command: ['yarn', 'serve']
    depends_on:
      - api
volumes:
  db:

